### ISSUE TITLE
 React native Module does not exist in the module map or in these directories 

### ISSUE THREAD

**Issue by akaiz** [solinor/paymenthighway-javascript-lib#13]
We are using Solinor in a react native app  but when we do import it we get this error message
" project_name/node_modules/paymenthighway/js/src/security/SecureSigner.js: Module does not exist in the module map or in these directories "

**Comment by Kostersson** [comment]
Which version of react-native are You using? 
Have You tried this:
1. Clear watchman watches: watchman watch-del-all.
2. Delete the node_modules folder: rm -rf node_modules && npm install.
3. Reset packager cache: rm -fr $TMPDIR/react-* or npm start -- --reset-cache.

**Comment by akaiz** [comment]
I tried running the above commands and I am using react native 0.41.2

**Comment by Swie** [comment]
Due to the server-side nature of this library, it typically should not be included in the client application.

Communication to Payment Highway APIs should be performed via the backend servers where the secret keys can be kept safe and secure. The card form parameters can be initialised in the backend and relayed to the client application e.g. by using a WebView. Alternatively our native Android (Java) and IOS (Swift) libraries can be used on the client side.

Here's an example of the server side functionality: https://github.com/solinor/paymenthighway-javascript-example

I'm closing this issue for now, however if there are further problems, please don't hesitate to raise a new one!
